FROM --platform=linux/amd64 rust:1.80

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    protobuf-compiler \
    libssl-dev \
    libpq-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY migrations ./migrations
COPY diesel.toml ./
COPY rust-toolchain.toml ./

RUN cargo build --release --bin maple

RUN mkdir -p /output && cp ./target/release/maple /output/

CMD ["/output/maple"]
